name: blue_archive_flutter_app
description: ブルアカ版育成情報アプリ
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/characters/all_character.csv
    - assets/icons/
    - assets/characters/chara/
    - assets/characters/skill/
    - assets/items/all_items.csv
    - assets/items/item_icons/